[pytest]
testpaths = tests
pythonpath = .
python_files = *_test.py
python_classes = Test*
python_functions = test_*

# Exibe o nome de cada teste executado
addopts =
    -v
    --tb=short
    --strict-markers