version: '3.8'

services:
  ifood-genai-agent:
    build: ../
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    environment:
      - ENV=dev
    command: uvicorn app.main:app --host
      - "


    