version: "3.8"

services:
  food-agent-api:
    build:
      context: ..
      dockerfile: docker/dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    environment:
      - ENV=dev
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped